### ISSUE TITLE
How to perform multi-classification tasks?

### ISSUE THREAD

**Issue by l1uw3n** [McGregorWwww/UCTransNet#11]
How to perform multi-classification tasks? I tried to modify the n_labels in config.py and got the following error. How can I modify it? Is there a problem with the mask I entered? What kind of mask should I use?
![image](https://user-images.githubusercontent.com/24247258/137882641-cd0eb435-c144-4dc5-b2bc-28ffae3f9db0.png)

**Comment by McGregorWwww** [comment]
Thanks for your attention. The dice loss provided in the submitted code is only for binary cases, as for multi-class cases, we use the TransUNet pipeline: https://github.com/Beckschen/TransUNet, you can download the pipeline and just change the model to UCTransNet. Hope this helps.

**Comment by l1uw3n** [comment]
@McGregorWwww After reading the transuet code, I still can't solve the multi classification problem. The multi classification problem of this project. Do I need to modify the activation function to realize multi classification in this project?

**Comment by McGregorWwww** [comment]
You also need to change the binary loss to multi-class loss.

**Comment by l1uw3n** [comment]
@McGregorWwww Can you add a multi-category example? I also encountered a problem when encoding the mask with one_hot.
Thank you very much if you can.

**Comment by Homecoming48** [comment]
For multi classification problems, in addition to modifying the loss function, what else should I modify? I hope the author can give guidance. Thank you very much
![7%Q)D~MB)K{QXC)E6)SVZX6](https://user-images.githubusercontent.com/80624596/173806805-5a3f0a6d-f51c-4e6c-be65-24b995e9f58a.png)

**Comment by McGregorWwww** [comment]
Maybe you can use the improve pipeline – UDTransNet (which is the journal version of UCTransNet) in [this link](https://github.com/McGregorWwww/UDTransNet)

Hope this helps.

**Comment by Homecoming48** [comment]
After I use UDTransNet, I can only modify the number of label in the config, but I still can't run it. Could you please give me some detailed steps? Thank you very much!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "McGregorWwww/UCTransNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月15日(星期三) 晚上6:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [McGregorWwww/UCTransNet] How to perform multi-classification tasks? (Issue #11)





 
Maybe you can use the improve pipeline – UDTransNet (which is the journal version of UCTransNet) in this link
 
Hope this helps.

**Comment by McGregorWwww** [comment]
Sorry, I'm not sure what is wrong with your experiment, do you follow the `README.md` in the UDTransNet repo? You only need to change the model to UCTransNet and the dataset settings in the config file. Or can you tell me the explicit problems you encountered?

**Comment by Homecoming48** [comment]
Thank you very much for your reply. My question is that my dataset format is (img.png&nbsp; &nbsp;And&nbsp; &nbsp;label.png), how can such a dataset format be divided into multiple segmentation? Thank you very much for your reply!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Haonan ***@***.***&gt;; 
发送时间: 2022年6月16日(星期四) 晚上11:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [McGregorWwww/UCTransNet] How to perform multi-classification tasks? (Issue #11)






对不起，我不确定你的实验有什么问题，你明白吗？README.md在 UD Trans Net repo 中？只需要将模型更改为 UCTrans Net 和配置文件中的数据集设置即可。或者你可以说出你遇到的显性问题。

—
直接回复此邮件，在 GitHub 上查看或取消订阅.
你收到这个是因为你评论了。留言 ID ***@***.***与&gt;

**Comment by McGregorWwww** [comment]
For customized dataset, you need to change the code of the `Load_data.py`, maybe you can find the loading script in other project that using your dataset. Or you can pre-process you dataset to .npz format to match that is used in this repo.
