### ISSUE TITLE
Other models' codes in the paper.

### ISSUE THREAD

**Issue by yuanc3** [McGregorWwww/UCTransNet#12]
Could you share the pytorch codes of the models in the paper for comparison? such as unet++, attUnet, MRUNet, TransUnet, Swin-Unet, and MedT.

**Comment by McGregorWwww** [comment]
UNet++: https://github.com/qubvel/segmentation_models.pytorch
Attention U-Net: https://github.com/bigmb/Unet-Segmentation-Pytorch-Nest-of-Unets
MultiResUNet: https://github.com/makifozkanoglu/MultiResUNet-PyTorch
TransUNet: https://github.com/Beckschen/TransUNet
Swin-Unet: https://github.com/HuCaoFighting/Swin-Unet
MedT: https://github.com/jeya-maria-jose/Medical-Transformer
