### ISSUE TITLE
about the details of three times five-fold cv

### ISSUE THREAD

**Issue by Schneey** [McGregorWwww/UCTransNet#14]
Hello, author.
I want to know the details of when you did three half-fold cross-validation. 
   1. Do you mix the train dataset and the test dataset, and then do a five-fold cross-validation? Or do five-fold cross-validation on the train dataset, and then test the best model on the test dataset each time?
   2. Is it convenient for you to provide the dataset you divided? Clas and MoNuSeg

Thanks

**Comment by McGregorWwww** [comment]
Thank for your attention.
1. The training and testing datasets are not mixed, I use the training set to do the CVs. In the testing phase, I test each best model of each fold and obtain the mean value and std.
2. The division of MoNuSeg is already given in the repository, for CV you should merge the Train and Val folders. As for the GlaS dataset, I just use the original division in the given links (train/test: 85/80) to perform CVs.
