### ISSUE TITLE
Have you finished the python script to train Unet model,so that can be as the pretrained_UNet_model_path = "./nets/best_model-UNet.pth.tar" to load?

### ISSUE THREAD

**Issue by wangwangwang978** [McGregorWwww/UCTransNet#18]

**Comment by McGregorWwww** [comment]
Thanks for your attention. The pre-training strategy is a two-step process, you need to train a U-Net from scratch first, then load its weights to train UCTransNet.

**Comment by kodsihirbazi** [comment]
Hi, I'm a beginner, can you please provide more specific information? How can I train a U-Net from scratch with your code? Can you show it with an example? Which .py file should be run or which part to modify etc.? I am a little bit confused.
