### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by Tmoork1996** [McGregorWwww/UCTransNet#19]
根据你给的requirements我安装了环境，下载了UCTransNet-MoNuSeg.pth.tar的预训练模型，运行后它显示RuntimeError: don't know how to restore data location of torch.FloatStorage (tagged with CUDA)。我的CUDA是11.1版本

**Comment by McGregorWwww** [comment]
你好，建议检查一下是不是用CPU跑的测试文件，这篇博客可能会有帮助：https://www.cnblogs.com/xiaodai0/p/10413711.html

**Comment by Tmoork1996** [comment]
> 你好，建议检查一下是不是用CPU跑的测试文件，这篇博客可能会有帮助：https://www.cnblogs.com/xiaodai0/p/10413711.html

谢谢，我在根据你提供的博客中更改后，又改了batch size，然后他又出现了下面这个问题
`RuntimeError: CUDA out of memory. Tried to allocate 50.00 MiB (GPU 0; 6.00 GiB total capacity; 2.09 GiB already allocated; 1.85 GiB free; 2.13 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`
请问是不是我的显卡内存不够运行。

**Comment by McGregorWwww** [comment]
> > 你好，建议检查一下是不是用CPU跑的测试文件，这篇博客可能会有帮助：https://www.cnblogs.com/xiaodai0/p/10413711.html
> 
> 谢谢，我在根据你提供的博客中更改后，又改了batch size，然后他又出现了下面这个问题 `RuntimeError: CUDA out of memory. Tried to allocate 50.00 MiB (GPU 0; 6.00 GiB total capacity; 2.09 GiB already allocated; 1.85 GiB free; 2.13 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF` 请问是不是我的显卡内存不够运行。

是的，显存不太够
