### ISSUE TITLE
8器官数据集其他器官测试结果

### ISSUE THREAD

**Issue by wangfan120** [McGregorWwww/UCTransNet#20]
你好，这论文中8器官数据集结果好像没有给出八类器官的每类器官的平均值，只给出总的平均dice值78.99，我想在我论文中详细对比每类器官结果，能否把每类器官测的结果发到我的邮箱 3461530462@qq.com，谢谢

**Comment by McGregorWwww** [comment]
请在以下链接下载：https://drive.google.com/file/d/1E-ZJLkNc0AJSUKI1CCWdcROMS9wERI9s/view?usp=sharing
