### ISSUE TITLE
Hello, I would like to ask, where is the ./nets/best_model-UNet.pth.tar file in this program, I hope to get your answer, thank you

### ISSUE THREAD

**Issue by lisongyu111** [McGregorWwww/UCTransNet#22]

**Comment by McGregorWwww** [comment]
Hello, thanks for your interest.
I'm sorry that the weight of the previously trained U-Net is missing, so you need to retrain the U-Net with the code and then load the weight if you want to use the pre-training strategy. 
At the moment we are not sure under what circumstances pre-training works well, so it is recommended to use the UCTransNet which is trained from scratch.

**Comment by lisongyu111** [comment]
Thanks for the reply, does this ./nets/best_model-UNet.pth.tar need to be derived from the UNet network in my own training code?



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Haonan ***@***.***&gt;; 
发送时间: 2022年3月23日(星期三) 中午12:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [McGregorWwww/UCTransNet] Hello, I would like to ask, where is the ./nets/best_model-UNet.pth.tar file in this program, I hope to get your answer, thank you (Issue #22)






您好，感谢您的兴趣。
很抱歉之前训练过的 U - Net 重量丢失了，所以如果想使用预训练策略，需要用代码重新训练 U - Network ，然后加载重量。
目前我们还不确定在什么情况下 pre - training 效果好，所以建议使用从零开始训练的 UC TransNet 。

—
直接回复此邮件，在 GitHub 上查看或取消订阅.
您收到这个消息是因为您编写了这个线程。留言 ID ***@***.***与&gt;

**Comment by McGregorWwww** [comment]
Yes.

**Comment by lisongyu111** [comment]
Excuse me, in this program, can U-Net in nets get best_model-UNet.pth.tar?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Haonan ***@***.***&gt;; 
发送时间: 2022年3月23日(星期三) 中午12:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [McGregorWwww/UCTransNet] Hello, I would like to ask, where is the ./nets/best_model-UNet.pth.tar file in this program, I hope to get your answer, thank you (Issue #22)





 
Yes.

**Comment by McGregorWwww** [comment]
You need to change the file name and path.

**Comment by lisongyu111** [comment]
thanks






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Haonan ***@***.***&gt;; 
发送时间: 2022年3月23日(星期三) 中午12:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [McGregorWwww/UCTransNet] Hello, I would like to ask, where is the ./nets/best_model-UNet.pth.tar file in this program, I hope to get your answer, thank you (Issue #22)





 
You need to change the file name and path.
