### ISSUE TITLE
Great Job！Hope to get your help

### ISSUE THREAD

**Issue by yang960526** [McGregorWwww/UCTransNet#23]
Good Job，Hope you can provide the comparative test code of Unet on the Synapse dataset，thanks!
zhaoyiyang526@gmail.com

**Comment by McGregorWwww** [comment]
Thanks for your attention.

For the testing phase of the Synapse dataset, we use the pipeline of [TransUNet](https://github.com/Beckschen/TransUNet), please refer to the `test.py`.

Or you can use the pipeline of UDTransNet (which is the journal version of UCTransNet) in [this link](https://github.com/McGregorWwww/UDTransNet) for testing five-fold results.

Hope this helps.

**Comment by yang960526** [comment]
Thank you very much, and good luck with your research

**Comment by McGregorWwww** [comment]
Thanks, if you have any other questions, feel free to contact me.
Good luck to you too.
