### ISSUE TITLE
网络结构图太好看了，已经一键三连，学长可以分享下网络结构的ppt吗？221055221@stdmail.gxust.edu.cn 

### ISSUE THREAD

**Issue by Yancccccc** [McGregorWwww/UCTransNet#24]

**Comment by McGregorWwww** [comment]
感谢
网络结构是用draw.io绘制的，抱歉暂时不便分享
软件学习成本不高，稍微摸索一下就可以画的很好看，相信自己哈哈

**Comment by Yancccccc** [comment]
哈哈，多谢学长分享，知道了draw.io这个软件。还想请问您 ，您是怎么 计算Dice Value的，是依次去掉U-Net的一个skip connection，数据放进改变的网络训练，然后分割图片 算出来的吗


| |
晏川
|
|
***@***.***
|
在2022年5月10日 21:16，Haonan ***@***.***> 写道：

感谢
网络结构是用draw.io绘制的，抱歉暂时不便分享
软件学习成本不高，稍微摸索一下就可以画的很好看，相信自己哈哈

**Comment by McGregorWwww** [comment]
你是指The Analysis of Skip connection这一节里的吗

**Comment by Yancccccc** [comment]
是的。         


| |
晏川
|
|
***@***.***
|
在2022年5月10日 21:25，Haonan ***@***.***> 写道：

你是指The Analysis of Skip connection这一节里的吗

**Comment by McGregorWwww** [comment]
是的，依次去掉skip，然后重新训练模型，再测试

**Comment by Yancccccc** [comment]
谢谢学长，过年就开始看您的UCTransNet,虽然我是做遥感的，但是下一篇文章就是医疗影像了，深受启发。


| |
晏川
|
|
***@***.***
|
在2022年5月10日 21:27，Haonan ***@***.***> 写道：

是的，依次去掉skip，然后重新训练模型，再测试

**Comment by McGregorWwww** [comment]
不客气，有问题可以随时联系，祝一切顺利

**Comment by Yancccccc** [comment]
再次叨扰下学长，请问您知道有医疗影像，怎么对肺结节打标签吗？LIDC_IDRL里面有何.xml文件包含结节的衡纵坐标，不知道他是怎么生成的。
| |
晏川
|
|
***@***.***
|
在2022年5月10日 21:34，Haonan ***@***.***> 写道：

不客气，有问题可以随时联系，祝一切顺利

**Comment by McGregorWwww** [comment]
这个确实不太了解，抱歉
