### ISSUE TITLE
Possible typo in encoding and token size

### ISSUE THREAD

**Issue by ilteralp** [McGregorWwww/UCTransNet#25]
Hi all, thanks a lot for sharing your code. I think there might be a small typo in embedding size and token size. The embedding size **$E_i$** is defined as follows in "Multi-scale Feature Embedding" subsection,

<img src="https://latex.codecogs.com/svg.image?\mathbf{E}_{i}&space;\in&space;\mathbb{R}&space;^{\frac{H&space;W}{i^{2}}&space;\times&space;C_{i}}" />
However, I think it should be,

<img src="https://latex.codecogs.com/svg.image?\mathbf{E}_{i}&space;\in&space;\mathbb{R}&space;^&space;{\frac{H&space;W}{2^{(i-1)^2}}&space;\times&space;C_{i}}" />

It's defined correctly for **$E_5$** in Figure 2 as below, 

<img src="https://latex.codecogs.com/svg.image?\mathbf{E}_{5}&space;\in&space;\mathbb{R}^{C_{5}&space;\times&space;\frac{H}{16}&space;\times&space;\frac{W}{16}}" />

The same applies to token size **$T_i$** as well.

**Comment by McGregorWwww** [comment]
Thanks for your attention and pointing out the typo!
Actually, the embedding size should be: 

$$\mathbb{R}^{\frac{H}{2^{(i-1)}} \times \frac{W}{2^{(i-1)}} \times C_i}$$

which is equivalent to 

$$\mathbb{R}^{\frac{HW}{2^{2(i-1)}} \times C_i}$$

Hope this helps!
