### ISSUE TITLE
可以分割具有多个分类的图片吗？

### ISSUE THREAD

**Issue by yuanyongqi2019** [McGregorWwww/UCTransNet#26]
程序里使用的数据集最后的输出类别都是1，如果是多个类别的程序应该如何修改呢？

**Comment by McGregorWwww** [comment]
请参考：Issue #23 
希望有帮助

**Comment by ManuJuice** [comment]
> 请参考：Issue #23 希望有帮助

你好，请问我使用png格式的数据集可以进行多类别目标的分割吗？
