### ISSUE TITLE
What is the number of channels for Synapse dataset ? 

### ISSUE THREAD

**Issue by ilteralp** [McGregorWwww/UCTransNet#27]
Hi all, thank you for sharing your code. I have question about the implementation for Synapse dataset. The number of channels is defined as `n_channels=3` in [config.py](https://github.com/McGregorWwww/UCTransNet/blob/3c687fdd04dffda0a1a134d58ae50762fb0307ef/Config.py#L20) file. However, this doesn't make sense for the Synapse dataset as each CT image has varying number of slices, from 85 to 198. 

Did you define the number of channels as 1 for Synapse dataset, as in the [config.py](https://github.com/McGregorWwww/UDTransNet/blob/570bb9e3b3fda82aa8631a0dad7f41b960509800/Config.py#L42) of UDTransNet ?

Best,
Melike

**Comment by McGregorWwww** [comment]
Thanks for your attention. 
You're right, we regard each slice of the CT as a gray-scale image and the num of channels is 1.
Hope this helps.
