### ISSUE TITLE
关于实验结果

### ISSUE THREAD

**Issue by Max-Well-Wang** [McGregorWwww/UCTransNet#28]
我使用您提供的MoNuSeg的训练验证及测试集，在两台不同得到服务器（Nvidia 3060Ti 和 Tesla T4）上分别训练了两次，Dice能保持在76%-78%之间，IOU保持在62%-64%之间。
但是，，，，换GlaS数据集，结果Dice47%-48%，Iou始终维持在：36%-37%？这也太离谱了！

**Comment by McGregorWwww** [comment]
您好，这可能是因为Transformer本身的计算方式导致的训练不稳定，尤其是在这种小数据集上表现更明显，目前我也在想办法解决，如果你有好的idea欢迎随时交流
