### ISSUE TITLE
多器官分割

### ISSUE THREAD

**Issue by lancy827** [McGregorWwww/UCTransNet#29]
您好，这个Load_Dataset,是给那两个其他数据集设计的吧，我从Transunet作者那里要到了多器官分割的数据集，我改怎么放置以及修改dataset能训练这个数据集呢？

**Comment by McGregorWwww** [comment]
您好，您可以直接在TransUNet的代码里把model换成UCTransNet，也可以使用这个pipeline：https://github.com/McGregorWwww/UDTransNet

希望能有帮助。

**Comment by lancy827** [comment]
非常感谢您！！



> 您好，您可以直接在TransUNet的代码里把model换成UCTransNet，也可以使用这个pipeline：https://github.com/McGregorWwww/UDTransNet
> 
> 希望能有帮助。

很高兴收到您的回复，非常感谢您！！！

**Comment by ManuJuice** [comment]
你好，请问你后面跑出来了吗？用png格式的可以跑吗？
