### ISSUE TITLE
网络输入大小问题

### ISSUE THREAD

**Issue by qzxxzq** [McGregorWwww/UCTransNet#32]
您好，很高兴能看到您这项令人惊喜的工作
我想在自己数据集上使用您这个网络，我的数据集大小是512*256的，请问需要如何修改呢？

**Comment by McGregorWwww** [comment]
你好，抱歉这么晚回复，希望你已经解决了，如果没有的话可以尝试两种方式：
1. 比较简单的一种就是训练时randomcrop，预测时resize到256*256输入，再把输出resize回去；
2. 另一种需要加一个新的size参数，可以参考https://github.com/McGregorWwww/UDTransNet （UCTransNet的升级版），在config里面添加了一个新的参数img_size2

**Comment by qzxxzq** [comment]
非常感谢您的回答
