### ISSUE TITLE
Minimal script to test the GLaS pretrained model on custom HE images?

### ISSUE THREAD

**Issue by ajinkya-kulkarni** [McGregorWwww/UCTransNet#34]
Hello team, thanks for this repo. I was wondering if there is any minimal script/notebook which I can use to test the GLaS pretrained model on custom HE images? I have a bunch of colon HE images, and I would like to see how well your pretrained model performs on identifying the glands. 

Best, Ajinkya

**Comment by McGregorWwww** [comment]
Thanks for attention.

Maybe the easiest way is to resize your images as those in GlaS dataset and build your file structure the same as that in README, then use the dataloader of GlaS.
