### ISSUE TITLE
Synapse dataset visualization

### ISSUE THREAD

**Issue by ChaohuanDeng123** [McGregorWwww/UCTransNet#36]
Hello, your work is excellent! I have a question about how to create colored graphs like Figure 7 in the article. Specifically, how is the Synapse dataset used to generate such colorful graphs? I am confused.

**Comment by McGregorWwww** [comment]
Thanks for your attention.

Here is the reference code: https://blog.csdn.net/qq_40475568/article/details/122012164?spm=1001.2014.3001.5501

**Comment by ChaohuanDeng123** [comment]
Thank you！

> Thanks for your attention.
> 
> Here is the reference code: https://blog.csdn.net/qq_40475568/article/details/122012164?spm=1001.2014.3001.5501
