### ISSUE TITLE
GlaS的验证集

### ISSUE THREAD

**Issue by xiaoyatang** [McGregorWwww/UCTransNet#37]
你好！
非常清晰和有启发性的工作！代码也很干净，感谢！最近在你们的模型上发现一些有意思的结果，但在reproduce GlaS数据集上结果的时候发现官方没有提供验证集，请问你们的验证集是怎么分的？并且在你们最新的工作https://github.com/McGregorWwww/UDTransNet上发现新的模型没有在GlaS上分验证集，这个链接里提供的.png和原数据集一致吗？

**Comment by McGregorWwww** [comment]
你好，感谢关注。

在这个工作中，我们采用了TransUNet给的划分；在UDTransNet上，为了使结果更可靠，我们采用了五折交叉验证的方式进行随机划分。
