### ISSUE TITLE
关于怎么跑通GlaS数据集

### ISSUE THREAD

**Issue by LIAMJOJO** [McGregorWwww/UCTransNet#38]
作者您好，我按照README建立了GlaS的文件夹，config文件更改了task_name但是运行train.py时出现如下报错，请问是什么原因呢
1.cv2.error: Caught error in DataLoader worker process 0.

2.cv2.error: OpenCV(4.5.1) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-kh7iq4w7\opencv\modules\imgproc\src\resize.cpp:4051: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'

请问还需要更改别的参数吗

**Comment by McGregorWwww** [comment]
你好，这个错误是因为数据集路径错了，请仔细检查，需要符合这个路径格式：https://github.com/McGregorWwww/UCTransNet/blob/efbff678801d9379b41221191d5df5922ed29443/Config.py#L39

**Comment by LIAMJOJO** [comment]
您好，我数据集的路径是UCTransNet-main\datasets\GlaS\XXXX_Folder，检查过应该是没有问题的，文件权限设置也应该没有问题。对下载数据集(.BPM)的Train做了68(train)和17(val)分类，另外标签图片是纯黑的，看您的论文Fig6中GlaS标签是黑白的，请问会是我下载的数据集的问题吗

**Comment by LIAMJOJO** [comment]
我在您的UD网络中找到了png格式的GlaS数据集，应该是图片格式问题，目前已经可以正常训练了 这对我有很大帮助 感谢您的帮助！
