### ISSUE TITLE
关于文章中对比试验复现出现的问题。

### ISSUE THREAD

**Issue by FansonWang** [McGregorWwww/UCTransNet#39]
学长，您好。当我把nets文件夹下的UCtransNet文件替换成TransUNet时，报错： File "/mnt/d/Python_Project/UCtransNet/utils.py", line 41, in forward  python-BaseException  assert(logit.shape==truth.shape) 。我在debug的过程中发现在Train_one_epoch.py文件中，执行完for i, (sampled_batch, names) in enumerate(loader, 1):之后sample_batch dict类型中‘label’张量的值均为0，而利用UCtransNet网络则不会出现这样的问题，我认为这是问题所在。除了train_model.py中为了让TransUNet能正常运行的相关修改外，我并未做其他任何修改。请问您在做对比实验时是否出现过类似的问题呢？如何解决呢？期待您的回复，祝您身体健康，一切顺利。   
train_model.py原第86行
 if model_type == 'TransUNet':
        parser = argparse.ArgumentParser()
        parser.add_argument('--vit_name', type=str,
                            default='R50-ViT-B_16', help='select one vit model')
        parser.add_argument('--img_size', type=int,
                            default=224, help='input patch size of network input')
        parser.add_argument('--vit_patches_size', type=int,
                            default=16, help='vit_patches_size, default is 16')
        args = parser.parse_args()
       
        config_vit = CONFIGS_ViT_seg[args.vit_name]
        config_vit.n_classes = 2
        config_vit.n_skip = 3
        if args.vit_name.find('R50') != -1:
            config_vit.patches.grid = (int(args.img_size / args.vit_patches_size), int(args.img_size / args.vit_patches_size))
        model = ViT_seg(config_vit, img_size=config.img_size, num_classes=config_vit.n_classes).cuda()#config_vit.n_classes=2

**Comment by CDUT-HZL** [comment]
你输出和GT出错了

**Comment by FansonWang** [comment]
我又重新debug了一下，发现是TransUNet模型本身的问题。经过pred=model(images)之后，pred张量中的值有负数，才导致后面计算loss出错了。您的代码没问题，感谢。

**Comment by CDUT-HZL** [comment]
这不是我的代码，我也是测试者，我也测试了Trans，直接移植需在pred上加Sig函数，不然loss会报错

**Comment by FansonWang** [comment]
看错ID了，哈哈。万分感谢您的指点啊，我被这个问题困扰好几天了，您一句话就让我恍然大悟了，代码跑通了，真的感谢您。

**Comment by LebronMX-A** [comment]
你好，我想请问一下使用TransUnet 的模型在这个train.py 训练之后的结果能作为对比实验嘛，能与作者文章里的结果对应上嘛.

**Comment by FansonWang** [comment]
> 你好，我想请问一下使用TransUnet 的模型在这个train.py 训练之后的结果能作为对比实验嘛，能与作者文章里的结果对应上嘛.
你好，我使用TransUnet 的模型利用MoNuSeg数据集在这个train.py 训练之后的结果为dice:77.45+1.36 iou:63.39+1.70.我觉得可以作为对比实验的结果。

**Comment by LebronMX-A** [comment]
感谢您的回答
当我使用这个train.py 训练transunet出现了这个错误
![image](https://github.com/user-attachments/assets/6231cd64-7c91-4b3f-80ed-73c5609d4ed0)

![image](https://github.com/user-attachments/assets/b87cb844-d094-4f42-ade7-3fcc8137011c)

**Comment by FansonWang** [comment]
> 感谢您的回答 当我使用这个train.py 训练transunet出现了这个错误 ![image](https://private-user-images.githubusercontent.com/57973807/380942208-6231cd64-7c91-4b3f-80ed-73c5609d4ed0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxNjcxNTUsIm5iZiI6MTczMDE2Njg1NSwicGF0aCI6Ii81Nzk3MzgwNy8zODA5NDIyMDgtNjIzMWNkNjQtN2M5MS00YjNmLTgwZWQtNzNjNTYwOWQ0ZWQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDAxNTQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwYWIzZjI2MmJkYzQ5YTk3NWYzMjcxNjQ1YzEyYTg2MjQ0ZmQzODhjZDA4Y2QxMmYzYzQ3ZTdhYWEyMTIxYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.iqrKrImiCL0lfAL9TczxUz5negdgHd04B-GigOYqFXA)
> 
> ![image](https://private-user-images.githubusercontent.com/57973807/380942236-b87cb844-d094-4f42-ade7-3fcc8137011c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxNjcxNTUsIm5iZiI6MTczMDE2Njg1NSwicGF0aCI6Ii81Nzk3MzgwNy8zODA5NDIyMzYtYjg3Y2I4NDQtZDA5NC00ZjQyLWFkZTctM2ZjYzgxMzcwMTFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDAxNTQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxNzFlZTE4ODdiMmJlM2U2MjYyYjMxYTMzMmZiNDZjYjY0NzhjNzZlNjY4MGE0MDNmYmQ0YzM5MWQ0NzdmMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.doz2w-YJp7iHgBhwnVxboMM5Tq7l6J_kbOSeBF-p728)

这是我的代码中对应的部分：
    elif model_type == 'TransUNet':
        config_vit = CONFIGS_ViT_seg[config.vit_name]
        config_vit.n_classes = config.num_classes
        config_vit.n_skip = config.n_skip
        if config.vit_name.find('R50') != -1:
            config_vit.patches.grid = (int(config.img_size / config.vit_patches_size), int(config.img_size / config.vit_patches_size))#224/16=14
        model = ViT_seg(config_vit, img_size=config.img_size, num_classes=config.n_labels).cuda()
    else: raise TypeError('Please enter a valid name for the model type')
其中 Config.py中
#TransUNet config in train_model.py
vit_name = 'R50-ViT-B_16'#select one vit model
vit_patches_size = 16#vit_patches_size, default is 16
num_classes = 1#output channel of network
n_skip = 3#using number of skip-connect, default is num
n_labels = 1
img_size = 224

我已经不从事CV方向的研究了，这是我之前做的，仅供参考。还有问题建议自己DeBug一下，一步一步看就能找到问题所在，祝顺利。

**Comment by LebronMX-A** [comment]
这对我很有帮助，感谢您的回复
