### ISSUE TITLE
test_model指标计算

### ISSUE THREAD

**Issue by wangfan120** [McGregorWwww/UCTransNet#5]
这指标计算test_model里写的是计算每张图的dice 再相加求平均吗，这跟利用整个三维数据套dice公式计算结果好像不一样（例如单张label全为0，而predicet不全为0），我看transUNet计算dice是调用binary源码好像是把三维数据展成一维再套公式

**Comment by wangfan120** [comment]
感觉指标这部分写的有问题，我用这模型就把数据换成promise12, 跑的结果dice跟参数total有关，把total设成test数据集的张数，结果dice只有0.47,再把整个model不变套到transUNet里，dice能到0.84

**Comment by McGregorWwww** [comment]
您好，我个人认为是TransUNet的代码有点问题，例如您提到的“单张label全为0，而predicet不全为0”这种情况，在TransUNet代码中将dice设为1，但参考dice公式我认为正确的做法应该是设为0，所以您用TransUNet代码dice高的原因应该也是在这。
有关这个问题您还可以参考https://github.com/Beckschen/TransUNet/issues/39
然而，为了和TransUNet实验保持一致性，在Synapse数据集我们用了他们的训练测试代码，只替换了模型，而GlaS和MoNuSeg用的是我们的代码。

**Comment by wangfan120** [comment]
谢谢您的答复，我已经明白了
