### ISSUE TITLE
multi-class trained error

### ISSUE THREAD

**Issue by yangyin2016** [McGregorWwww/UCTransNet#6]
Thanks  for your good work，if this code just for one class，when i used to train mutil-classs model，i got error

**Comment by McGregorWwww** [comment]
Thanks for attention. For multi-class cases, we use the pipeline of TransUNet: https://github.com/Beckschen/TransUNet, hope this helps.

**Comment by yangyin2016** [comment]
thank you for your response, I really appreciate it，the mutil-class is trained successfully.
