### ISSUE TITLE
Question about the ''CCT'' block

### ISSUE THREAD

**Issue by JackHeroFly** [McGregorWwww/UCTransNet#9]
Hello author,thanks for your code.In my concerning, you just project the patches into the shape of ''Batch x 196 x 64、Batchsize x 196 x 128、Batchsize x 196 x 256、Batchsize x 196 x 512‘’. '196' is the number of patches.  64、128、256 and 512 are the enbedding dimensions and they are just equalling with the channel dimension,but not the real channel dimmension.So,could you tell me the difference of CCT oepration and original self-attention?Look forward to your reply.

**Comment by McGregorWwww** [comment]
Thanks for your attention. The main differences from SA are 1) the Q and KV in CCT is different (in SA, Q=K=V), Q is from one scale and KV are the concatenated result of four scales (see Figure 5); 2) the operation axis in SA is patch-axis (in your example: 196) and in CCT is channel-axis (in your example: 64, 128, ...) (see Figure 4). Hope this helps.

**Comment by JackHeroFly** [comment]
> Thanks for your attention. The main differences from SA are 1) the Q and KV in CCT is different (in SA, Q=K=V), Q is from one scale and KV are the concatenated result of four scales (see Figure 5); 2) the operation axis in SA is patch-axis (in your example: 196) and in CCT is channel-axis (in your example: 64, 128, ...) (see Figure 4). Hope this helps.

Thanks for your detailed reply.Actually,Your embedding codes "x = self.patch_embeddings(x)
        x = x.flatten(2)
        x = x.transpose(-1, -2)  # (B, n_patches, hidden)
        embeddings = x + self.position_embeddings
        embeddings = self.dropout(embeddings)'' are the same with TransUnet.So,I cannot understand your CCT clearly.

**Comment by McGregorWwww** [comment]
> > Thanks for your attention. The main differences from SA are 1) the Q and KV in CCT is different (in SA, Q=K=V), Q is from one scale and KV are the concatenated result of four scales (see Figure 5); 2) the operation axis in SA is patch-axis (in your example: 196) and in CCT is channel-axis (in your example: 64, 128, ...) (see Figure 4). Hope this helps.
> 
> Thanks for your detailed reply.Actually,Your embedding codes "x = self.patch_embeddings(x) x = x.flatten(2) x = x.transpose(-1, -2) # (B, n_patches, hidden) embeddings = x + self.position_embeddings embeddings = self.dropout(embeddings)'' are the same with TransUnet.So,I cannot understand your CCT clearly.

The differences are in Attention_org module.

**Comment by JackHeroFly** [comment]
> > > Thanks for your attention. The main differences from SA are 1) the Q and KV in CCT is different (in SA, Q=K=V), Q is from one scale and KV are the concatenated result of four scales (see Figure 5); 2) the operation axis in SA is patch-axis (in your example: 196) and in CCT is channel-axis (in your example: 64, 128, ...) (see Figure 4). Hope this helps.
> > 
> > 
> > Thanks for your detailed reply.Actually,Your embedding codes "x = self.patch_embeddings(x) x = x.flatten(2) x = x.transpose(-1, -2) # (B, n_patches, hidden) embeddings = x + self.position_embeddings embeddings = self.dropout(embeddings)'' are the same with TransUnet.So,I cannot understand your CCT clearly.
> 
> The differences are in Attention_org module.

Thank you very much.If I use you codes,I will cite your paper.
